<?php
/**
 * @file
 * EAN search
 */


/**
 * Implements hook_search_info().
 */
function ean_search_search_info() {
  return array(
    'title' => 'Hotels search',
    'path' => 'ean_search',
  );
}

/**
 * Implements hook_search_execute().
 */
function ean_search_search_execute($keys = NULL, $conditions = NULL) {
  $hotels = array();

  $data = ean_region($keys);
  foreach ($data['HotelList']['HotelSummary'] as $hotel) {
    $snippet = theme('ean_search_results', array('hotel' => $hotel));
    $hotels[] = array(
      'title' => $hotel['name'],
      'link' => $hotel['deepLink'],
      'snippet' => $snippet,
    );
  }

  return $hotels;
}


/**
 * Submits the user's input.
 */
function ean_search_block_submit($form, &$form_state) {
  $destination = $form_state['input']['destination'];
  drupal_set_message(
    t(
      'Searching for @destination',
      array(
        '@destination' => $destination,
      )
    )
  );

  $hotelList = ean_region($destination);
}
