<?php

/**
 * @file
 * This is the file which contains all the global config settings for EAN.
 */

define('EAN_OPERATIONS', 'list,avail,info');
define('EAN_URL', 'http://api.ean.com/ean-services/rs/hotel/v3/');

/**
 * Implements hook_menu().
 */
function ean_menu() {
  $items = array();

  $items['admin/config/services/ean'] = array(
    'title' => 'Global EAN config',
    'description' => 'The main place to enter your global EAN data, such as CID and key',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ean_admin'),
    'access arguments' => array('administer ean'),
    'file' => 'ean.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/services/ean/test'] = array(
    'title' => 'Test',
    'description' => 'Tests the connection with the EAN API',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ean_settings_test'),
    'access arguments' => array('administer ean'),
    'file' => 'ean.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/services/ean/api'] = array(
    'title' => 'Settings',
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function ean_permission() {
  return array(
    'administer ean' => array(
      'title' => t('Administer EAN'),
      'description' => t('Administer the Expedia Affiliate Network.'),
    ),
  );
}

/* EAN API functions */

/**
 * Retrieves the info about a hotel from the Expedia Affiliate Network.
 */
function ean_hotel_info($hotelid) {
  $params = array(
    'hotelId' => $hotelid,
    'options' => 'DEFAULT',
  );

  $info = ean_http_request('info', $params);
  $info = $info['HotelInformationResponse'];

  return $info;
}

/**
 * Retrieves a list of hotels based on a reagion string from EAN.
 */
function ean_region($destination) {
  $params = array(
    'destinationString' => $destination,
    'options' => 'DEFAULT',
  );

  $list = ean_http_request('list', $params);
  $list = $list['HotelListResponse'];

  foreach ($list['HotelList']['HotelSummary'] as &$hotel) {
    $hotel['name'] = ean_make_html($hotel['name']);
    $hotel['deepLink'] = ean_make_html($hotel['deepLink']);
  }

  return $list;
}

/**
 * Replace the HTML encoded characters by actual HTML.
 */
function ean_make_html($string) {
  $string = str_replace('&gt;', '>', $string);
  $string = str_replace('&lt;', '<', $string);
  $string = str_replace('&amp;', '&', $string);

  return $string;
}

/**
 * Actually make a request to the EAN webservice.
 */
function ean_http_request($operation, $params, $locale = NULL) {
  $request_elements = array(
    'cid' => variable_get('ean_cid'),
    'apiKey' => variable_get('ean_key'),
    'minorRev' => 16,
    '_type' => 'json',
  );

  $valid_ops = explode(',', EAN_OPERATIONS);

  // Check if operation is valid.
  if (!in_array($operation, $valid_ops)) {
    watchdog('ean', "You must provide a valid operation", NULL, WATCHDOG_ERROR);
    drupal_set_message(t('EAN module: %op is not valid operation given', $operation));
    return FALSE;
  }

  // Check if a cid is set.
  if (empty($request_elements['cid'])) {
    watchdog('ean', "No CID configured", NULL, WATCHDOG_ERROR);
    drupal_set_message(t('EAN module: No CID set, please contact your site administrator'));
    return FALSE;
  }

  // Check if key is set.
  if (empty($request_elements['apiKey'])) {
    watchdog('ean', "No key configured", NULL, WATCHDOG_ERROR);
    drupal_set_message(t('EAN module: No key set, please contact your site administrator'));
    return FALSE;
  }

  $request_elements = array_merge($request_elements, $params);
  $url = url(
    EAN_URL . $operation,
    array(
      'query' => $request_elements,
    )
  );
  watchdog('ean', $url, NULL, WATCHDOG_NOTICE);
  $contents = drupal_http_request(
    $url
  );

  $data = drupal_json_decode($contents->data);
  return $data;
}
