<?php
/**
 * @file
 * Install, update, and uninstall functions for the en_hotel module.
 */

/**
 * Implements hook_field_schema().
 */
function ean_hotel_field_schema($field) {
  $columns = array(
    'ean_hotel_id' => array(
      'type' => 'int',
      'length' => 8,
      'not null' => FALSE,
    ),
  );

  $indexes = array(
    'ean_hotel_id' => array('ean_hotel_id'),
  );

  return array(
    'columns' => $columns,
    'indexes' => $indexes,
  );
}
