<?php
/**
 * @file
 * EAN hotel
 */

/**
 * Implements hook_field_info().
 */
function ean_hotel_field_info() {
  return array(
    'ean_hotel_hotelid' => array(
      'label' => t('Hotel id'),
      'description' => t('Stores the hotel id of a EAN hotel'),
      'default_widget' => 'ean_hotel_hotelid_widget',
      'default_formatter' => 'ean_hotel_hotelid_formatter',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function ean_hotel_field_widget_info() {
  return array(
    'ean_hotel_hotelid_widget' => array(
      'label' => t('EAN hotelid'),
      'field types' => array('ean_hotel_hotelid'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function ean_hotel_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $element['ean_hotel_id'] = array(
    '#title' => t('EAN hotel id'),
    '#type' => 'textfield',
    '#default_value' => $items[$delta],
  );

  return $element;
}

/**
 * Implements hook_field_is_empty().
 */
function ean_hotel_field_is_empty($item, $field) {
  if (empty($item['ean_hotel_id'])) {
    return TRUE;
  } else {
    return FALSE;
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function ean_hotel_field_formatter_info() {
  return array(
    'ean_hotel_hotelid_formatter' => array(
      'label' => t('The full hotel'),
      'field types' => array('ean_hotel_hotelid'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function ean_hotel_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  foreach ($items as $delta => $item) {
    $data = ean_hotel_info($item['ean_hotel_id']);
    $snippet = theme('ean_hotel_info', array('hotel' => $data));
    dsm($data);
    $element[] = array(
      '#markup' => $snippet,
    );
  }

  return $element;
}

