<?php

/**
 * @file
 * This is the file which contains all the global config zettings for EAN.
 */

/**
 * Implements hook_menu().
 */
function ean_config_menu() {
  $items = array();

  $items['admin/config/services/ean'] = array(
    'title' => 'Global EAN config',
    'description' => t('The main place to enter your global EAN data, such as CID and key'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ean_config_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ean_config_settings.form.inc',
  );

  return $items;
}
